gates:
  - id: 1
    position: [0.0, -3.0, 4.0]
    orientation: [0.0, 0.0, 0.0]
  - id: 2
    position: [-1.5, -1.5, 4.0]
    orientation: [0.0, 0.0, 1.57079632679]  # pi/2
  - id: 3
    position: [0.0, 0.0, 4.0]
    orientation: [0.0, 0.0, 0.0]
  - id: 4
    position: [1.5, 1.5, 5.0]
    orientation: [0.0, 0.0, 1.57079632679]  # pi/2
  - id: 5
    position: [0.0, 3.0, 4.0]
    orientation: [0.0, 0.0, 0.0]
  - id: 6
    position: [-1.5, 1.5, 6.0]
    orientation: [0.0, 0.0, 1.57079632679]  # pi/2
  - id: 7
    position: [0.0, 0.0, 4.0]
    orientation: [0.0, 0.0, 0.0]
  - id: 8
    position: [1.5, -1.5, 4.0]
    orientation: [0.0, 0.0, 1.57079632679]  # pi/2

starting_positions:
  - [1.0, -3.0, 4.0]
  - [-1.5, -2.5, 4.0]
  - [-1.0, 0.0, 4.0]
  - [1.5, 0.5, 5.0]
  - [1.0, 3.0, 4.0]
  - [-1.5, 2.5, 6.0]
  - [1.5, -0.5, 4.0]
